Models/Pelicula.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace ClaseMVC.Models
{
    public enum Categoria
    {
        [Display(Name = "Ciencia Ficcion")]
        Ficcion,
        Drama,
        [Display(Name = "comedia")]
        Comedia
    }

    public class Pelicula
    {
        public int id { get; set; }
        [Required(ErrorMessage="*")]
        public string Titulo { get; set; }
        [Required(ErrorMessage = "*")]
        public string ActorPrincipal { get; set; }
               
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Fecha { get; set; }

        public decimal Precio { get; set; }

        public Categoria? Categoria { get; set; }
        public string ruta { get; set; }
    }

    public class PeliculaDBContext : DbContext
    {
        public PeliculaDBContext()
            : base("PeliculaConnection")
        {
        }

        public DbSet<Pelicula> peliculas { get; set; }
    }
}

Controllers/PeliculaController.cs
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using ClaseMVC.Models;
using System.Web;
using PagedList;

namespace ClaseMVC.Controllers
{
    public class PeliculaController : Controller
    {
        private PeliculaDBContext db = new PeliculaDBContext();

        //
        // GET: /Pelicula/

        public ActionResult Index(int pagina = 1)
        {
            return View(db.peliculas.ToList().ToPagedList(pagina,14));
        }

        //
        // GET: /Pelicula/Details/5

        public ActionResult Details(int id = 0)
        {
            Pelicula pelicula = db.peliculas.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        public ActionResult llamarAPI()
        {
            return View();
        }

        //
        // GET: /Pelicula/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Pelicula/Create

        [HttpPost]
        public ActionResult Create(Pelicula pelicula, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/imagenes"), fileName);
                    file.SaveAs(path);
                    //path = Url.Content(Path.Combine("~/Content/imagenes", fileName));
                    path = "/content/imagenes/" + fileName;
                    pelicula.ruta = path;
                }
                db.peliculas.Add(pelicula);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(pelicula);
            //if (ModelState.IsValid)
            //{
            //    db.peliculas.Add(pelicula);
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}

            //return View(pelicula);
        }

        //
        // GET: /Pelicula/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Pelicula pelicula = db.peliculas.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        //
        // POST: /Pelicula/Edit/5

        [HttpPost]
        public ActionResult Edit(Pelicula pelicula, HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/imagenes"), fileName);
                file.SaveAs(path);
                //path = Url.Content(Path.Combine("~/Content/imagenes", fileName));
                path = "/content/imagenes/" + fileName;
                pelicula.ruta = path;
            }
            db.Entry(pelicula).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");

            //if (ModelState.IsValid)
            //{
            //    db.Entry(pelicula).State = EntityState.Modified;
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}
            //return View(pelicula);
        }

        //
        // GET: /Pelicula/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Pelicula pelicula = db.peliculas.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        //
        // POST: /Pelicula/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Pelicula pelicula = db.peliculas.Find(id);
            db.peliculas.Remove(pelicula);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/Pelicula/Create.cshtml
@model ClaseMVC.Models.Pelicula

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Pelicula", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Pelicula</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Titulo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Titulo)
            @Html.ValidationMessageFor(model => model.Titulo)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Categoria)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Categoria,Enum.GetNames(typeof(ClaseMVC.Models.Categoria)).Select(e => new SelectListItem { Text = e }))
            @Html.ValidationMessageFor(model => model.Categoria)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ActorPrincipal)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ActorPrincipal)
            @Html.ValidationMessageFor(model => model.ActorPrincipal)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Fecha)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Fecha)
            @Html.ValidationMessageFor(model => model.Fecha)
        </div>
        
        <div class="display-label">
            Image:
        </div>
        <div class="display-field">
            <img id="imagePelicula" alt="" src="" width="100px" height="100px"/>
            @Html.HiddenFor(model => model.ruta)
        </div>
        
        <div class="display-field">
            <input type="file" id="file" name="file"/>
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/rating")
    <script type="text/jscript">
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#imagePelicula').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#file").change(function () {
            readURL(this);
        });

    </script>
       

}

Views/Pelicula/Delete.cshtml
@model ClaseMVC.Models.Pelicula

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Pelicula</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Titulo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Titulo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ActorPrincipal)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ActorPrincipal)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Fecha)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fecha)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Views/Pelicula/Details.cshtml
@model ClaseMVC.Models.Pelicula

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Pelicula</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Titulo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Titulo)
    </div>
    
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Categoria)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Categoria)
    </div>
    
    <div class="display-label">
         Image
    </div>
    <div class="display-field">
         <img alt="Model.Titulo" src="@Url.Content("~" + Model.ruta)" width="100px" height="100px"/>
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ActorPrincipal)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ActorPrincipal)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Fecha)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fecha)
    </div>
    
    
   
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Pelicula/Edit.cshtml
@model ClaseMVC.Models.Pelicula

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Pelicula", FormMethod.Post, new { enctype = "multipart/form-data" })) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Pelicula</legend>

        @Html.HiddenFor(model => model.id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Titulo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Titulo)
            @Html.ValidationMessageFor(model => model.Titulo)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Categoria)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Categoria,Enum.GetNames(typeof(ClaseMVC.Models.Categoria)).Select(e => new SelectListItem { Text = e }))
            @Html.ValidationMessageFor(model => model.Categoria)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ActorPrincipal)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ActorPrincipal)
            @Html.ValidationMessageFor(model => model.ActorPrincipal)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Fecha)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Fecha)
            @Html.ValidationMessageFor(model => model.Fecha)
        </div>
        
        <div class="display-label">
            Image:
        </div>
        <div class="display-field">
            <img id="imagePelicula" alt="Model.Titulo" src="@Url.Content("~" + Model.ruta)" width="100px" height="100px"/>
            @Html.HiddenFor(model => model.ruta)
        </div>
        
        <div class="display-field">
            <input type="file" id="file" name="file"/>
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/rating")
    <script type="text/jscript">
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#imagePelicula').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#file").change(function () {
            readURL(this);
        });

    </script>
       

}

Views/Pelicula/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<ClaseMVC.Models.Pelicula>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>



<ul id="album-list">
    
    @foreach (var pel in Model)
    {
        <li>
            <a href="@Url.Action("Details", new {id=pel.id})">

                    
                    
                <img alt="@pel.Titulo" src="@Url.Content("~" + pel.ruta)" width="100px" height="100px"/>
                   
                <span>@pel.Titulo</span>
            </a>
        </li>
    }
</ul>

<div class="pager" data-otf-target="#album-list">
    @Html.PagedListPager(Model, pagina => Url.Action("Index", new {pagina}), PagedListRenderOptions.MinimalWithItemCountText)
</div>


@*<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ActorPrincipal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ActorPrincipal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>*@

Views/Pelicula/Index2.cshtml
@model IEnumerable<ClaseMVC.Models.Pelicula>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<ul id="album-list">
        @foreach (var pel in Model)
        {
            <li>
                <a href="@Url.Action("Details", new {id=pel.id})">

                    
                    
                    <img alt="@pel.Titulo" src="@Url.Content("~" + pel.ruta)" width="100px" height="100px"/>
                   
                    <span>@pel.Titulo</span>
                </a>
            </li>
        }
    </ul>

@*<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ActorPrincipal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ActorPrincipal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>*@

Views/Pelicula/Index_old.cshtml
@model IEnumerable<ClaseMVC.Models.Pelicula>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ActorPrincipal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ActorPrincipal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

Views/Pelicula/LlamarAPI.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<ClaseMVC.Models.Pelicula>

@{
    ViewBag.Title = "Llamar API con Jquery";
}

<h2>Llamar API con JQuery</h2>

<div>
    <div>
        <h1>Peliculas</h1>
        <input id="buscar" type="button" value="Buscar"/>
    </div>
    <div>
        <ul id="album-list"></ul>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function() {
            $('#buscar').click(function() {
                var loc = window.location.pathname;
                //var loc = "http://localhost:55092/";
                var dir = loc.substring(0, loc.lastIndexOf('/'));
                var appdir = dir.substring(0, dir.lastIndexOf('/'));
                //var apiurl = appdir + "/api/peliculas";

                var apiurl = "http://localhost/webapi/api/peliculas";

                $('#album-list').empty();
                $.getJSON(apiurl, function(data) {
                    $.each(data, function(i, pelicula) {

                        var html = $('<li> <img src="' + appdir +
                            pelicula.ruta + '"width="100px" heigth="100px" alt="'
                            + pelicula.Titulo + '">' + pelicula.Titulo + '</li>');
                        $('#album-list').append(html);
                    });
                });
            });
        });
    </script>
}